spring.application.name=knowledge-assistant

knowledge-assistant.gemini.api-key=${GEMINI_API_KEY}
knowledge-assistant.gemini.chat-model=gemini-2.5-flash
knowledge-assistant.gemini.embedding-model=gemini-embedding-001

knowledge-assistant.qdrant.host=${QDRANT_HOST:807007b7-529a-4000-9676-ece6ce56b4d0.eu-central-1-0.aws.cloud.qdrant.io}
knowledge-assistant.qdrant.port=${QDRANT_PORT:6334}
knowledge-assistant.qdrant.collection-name=${QDRANT_COLLECTION:documents}
knowledge-assistant.qdrant.vector-size=3072
knowledge-assistant.qdrant.api-key=${QDRANT_API_KEY}


knowledge-assistant.documents.chunk-size=${DOCUMENT_CHUNK_SIZE:1000}
knowledge-assistant.documents.chunk-overlap=${DOCUMENT_CHUNK_OVERLAP:200}
knowledge-assistant.documents.max-upload-size=${DOCUMENT_MAX_UPLOAD_SIZE:10MB}
knowledge-assistant.retrieval.max-results=${RETRIEVAL_MAX_RESULTS:3}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#<spring.datasource.url=jdbc:postgresql://localhost:5432/knowledge_assistant
#spring.datasource.username=admin
#spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=${knowledge-assistant.documents.max-upload-size}
spring.servlet.multipart.max-request-size=${knowledge-assistant.documents.max-upload-size}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
server.error.include-message=never
